document.addEventListener("DOMContentLoaded",function(event){class Button{constructor(buttonElement){this.block=buttonElement;this.init();this.initEvents()}
init(){const el=gsap.utils.selector(this.block);this.DOM={button:this.block,flair:el(".button__flair"),};this.xSet=gsap.quickSetter(this.DOM.flair,"xPercent");this.ySet=gsap.quickSetter(this.DOM.flair,"yPercent")}
getXY(e){const{left,top,width,height}=this.DOM.button.getBoundingClientRect();const xTransformer=gsap.utils.pipe(gsap.utils.mapRange(0,width,0,100),gsap.utils.clamp(0,100));const yTransformer=gsap.utils.pipe(gsap.utils.mapRange(0,height,0,100),gsap.utils.clamp(0,100));return{x:xTransformer(e.clientX-left),y:yTransformer(e.clientY-top),}}
initEvents(){this.DOM.button.addEventListener("mouseenter",(e)=>{const{x,y}=this.getXY(e);this.xSet(x);this.ySet(y);gsap.to(this.DOM.flair,{scale:1,duration:0.8,ease:"power2.out",})});this.DOM.button.addEventListener("mouseleave",(e)=>{const{x,y}=this.getXY(e);gsap.killTweensOf(this.DOM.flair);gsap.to(this.DOM.flair,{xPercent:x>90?x+20:x<10?x-20:x,yPercent:y>90?y+20:y<10?y-20:y,scale:0,duration:0.6,ease:"power2.out",})});this.DOM.button.addEventListener("mousemove",(e)=>{const{x,y}=this.getXY(e);gsap.to(this.DOM.flair,{xPercent:x,yPercent:y,duration:0.8,ease:"power2",})})}}
const buttonElements=document.querySelectorAll('[data-block="button"]');buttonElements.forEach((buttonElement)=>{new Button(buttonElement)});if(document.querySelector(".page-id-5952")){gsap.utils.toArray(".shutter-cards-row").forEach((cover)=>{gsap.set(cover,{width:"100%"});gsap.to(cover,{width:"0%",duration:2,ease:"power2.out",scrollTrigger:{trigger:cover,start:"top 50%",toggleActions:"play none none none",},})});gsap.utils.toArray(".blink-card-row").forEach((row)=>{gsap.set(row.querySelectorAll(".blink-card"),{opacity:0});gsap.to(row.querySelectorAll(".blink-card"),{opacity:1,duration:3,stagger:0.3,ease:"power2.out",scrollTrigger:{trigger:row,start:"top 50%",toggleActions:"play none none none",},})})}
function horizontalLoop(items,config){items=gsap.utils.toArray(items);config=config||{};let tl=gsap.timeline({repeat:config.repeat,paused:config.paused,defaults:{ease:"none"},onReverseComplete:()=>tl.totalTime(tl.rawTime()+tl.duration()*100),}),length=items.length,startX=items[0].offsetLeft,times=[],widths=[],xPercents=[],curIndex=0,pixelsPerSecond=(config.speed||1)*100,snap=config.snap===!1?(v)=>v:gsap.utils.snap(config.snap||1),totalWidth,curX,distanceToStart,distanceToLoop,item,i;gsap.set(items,{xPercent:(i,el)=>{let w=(widths[i]=parseFloat(gsap.getProperty(el,"width","px")));xPercents[i]=snap((parseFloat(gsap.getProperty(el,"x","px"))/w)*100+gsap.getProperty(el,"xPercent"));return xPercents[i]},});gsap.set(items,{x:0});totalWidth=items[length-1].offsetLeft+(xPercents[length-1]/100)*widths[length-1]-startX+items[length-1].offsetWidth*gsap.getProperty(items[length-1],"scaleX")+(parseFloat(config.paddingRight)||0);for(i=0;i<length;i++){item=items[i];curX=(xPercents[i]/100)*widths[i];distanceToStart=item.offsetLeft+curX-startX;distanceToLoop=distanceToStart+widths[i]*gsap.getProperty(item,"scaleX");tl.to(item,{xPercent:snap(((curX-distanceToLoop)/widths[i])*100),duration:distanceToLoop/pixelsPerSecond,},0).fromTo(item,{xPercent:snap(((curX-distanceToLoop+totalWidth)/widths[i])*100),},{xPercent:xPercents[i],duration:(curX-distanceToLoop+totalWidth-curX)/pixelsPerSecond,immediateRender:!1,},distanceToLoop/pixelsPerSecond).add("label"+i,distanceToStart/pixelsPerSecond);times[i]=distanceToStart/pixelsPerSecond}
function toIndex(index,vars){vars=vars||{};Math.abs(index-curIndex)>length/2&&(index+=index>curIndex?-length:length);let newIndex=gsap.utils.wrap(0,length,index),time=times[newIndex];if(time>tl.time()!==index>curIndex){vars.modifiers={time:gsap.utils.wrap(0,tl.duration())};time+=tl.duration()*(index>curIndex?1:-1)}
curIndex=newIndex;vars.overwrite=!0;return tl.tweenTo(time,vars)}
tl.next=(vars)=>toIndex(curIndex+1,vars);tl.previous=(vars)=>toIndex(curIndex-1,vars);tl.current=()=>curIndex;tl.toIndex=(index,vars)=>toIndex(index,vars);tl.times=times;tl.progress(1,!0).progress(0,!0);if(config.reversed){tl.vars.onReverseComplete();tl.reverse()}
return tl}
window.addEventListener("load",function(e){if(jQuery("body").find(".cs-next-project").hasClass("cs-next-project")==!0){const next_projects=gsap.utils.toArray(".single-next-project");const loop=horizontalLoop(next_projects,{paused:!0,repeat:-1,});loop.play()}
if(jQuery("body").find(".banner-logos").hasClass("banner-logos")==!0){gsap.to(".banner-logos-parent",{opacity:1,duration:2,ease:"expoScale(0.5,7,none)",});const banner_logos=gsap.utils.toArray(".banner-single-logo");const banner_logos_loop=horizontalLoop(banner_logos,{paused:!0,repeat:-1,});banner_logos_loop.play();setTimeout(function(){banner_logos_loop.play()},1000)}},!1);gsap.registerPlugin(ScrollTrigger);pinGroupContent=gsap.utils.toArray(".animate-it");gsap.set(pinGroupContent,{y:40,ease:"none",});const enterConfig={y:0,duration:0.4,ease:"none",};pinGroupContent.forEach((e,i)=>{ScrollTrigger.create({trigger:e,start:"top 82%",end:"bottom top",onEnter:()=>gsap.to(e,enterConfig),onEnterBack:()=>gsap.to(e,enterConfig),onLeave:()=>gsap.to(e,{y:-40,duration:0.4,ease:"none",}),onLeaveBack:()=>gsap.to(e,{y:40,duration:0.4,ease:"none",}),})});if(jQuery("body").find(".about-banner").hasClass("about-banner")==!0){const timelineHeader=gsap.timeline({scrollTrigger:{id:"ZOOM",trigger:".about-banner",scrub:0.5,start:"top top",end:"+=100% top",pin:!0,toggleActions:"restart pause resume pause",},});let bannerHeight=document.querySelector(".about-banner").offsetHeight;timelineHeader.to(".banner-anim-box .upper-part",{top:"-500px"},"sameTime").to(".banner-anim-box .lower-part",{bottom:"-200px"},"sameTime").to(".about-banner",{paddingTop:"80px",paddingBottom:"80px"},"secondSameTime").to(".about-banner .video-box",{height:bannerHeight-160+`px`,width:"100%"},"secondSameTime").to(".about-banner .video-box .video-overlay",{background:"transparent"},"secondSameTime");const pinWrapper=document.querySelector(".scroller-wrapper");function getScrollAmount(){let pinWrapperWidth=pinWrapper.scrollWidth;return-(pinWrapperWidth-window.innerWidth)}
const pinTween=gsap.to(pinWrapper,{x:getScrollAmount,duration:3,ease:"none",});ScrollTrigger.create({trigger:".scroller-wrapper",start:"top top",end:()=>`+=${getScrollAmount() * -1}`,pin:!0,animation:pinTween,scrub:!0,invalidateOnRefresh:!0,})}})